// Hand-drawn by the artist; data only. Generated from art/egg0/egg0.art by art/build.py
import type { PetSheet } from '../pets.ts'

export const EGG0_SHEET: PetSheet = {
  w: 24,
  h: 16,
  palette: {"o":"#2b1f2a","W":"#fffdf6","L":"#f7ecd6","B":"#e9d5b0","D":"#c9a985","p":"#d77757","q":"#a8553b","s":"#26262e"},
  animations: {
    "idle": { loop: true, frames: [
      { ms: 1500, head: [12,1], px: ["........................","..........oooo..........",".........oLLLLo.........","........oLLLLLBo........",".......oLWWLLLBDo.......",".......oLWLLLBBDo.......","......oLLLLBBBBDDo......","......oLLLBBBBBDDo......","......oLLBBBBBBDDo......","......oLBBBBBBBqDo......","......oLBBBBBBBDDo......","......oBBpBBBBBDDo......",".......oDBBBBBDDo.......","........oDqDDDDo........",".........oooooo.........","........ssssssss........"], exit: true },
      { ms: 80, head: [12,1], px: ["........................","..........oooo..........",".........oLLLWo.........","........oLLLWLBo........",".......oLWWWLLBDo.......",".......oLWWLLBBDo.......","......oLLWLBBBBDDo......","......oLWLBBBBBDDo......","......oLLBBBBBBDDo......","......oLBBBBBBBqDo......","......oLBBBBBBBDDo......","......oBBpBBBBBDDo......",".......oDBBBBBDDo.......","........oDqDDDDo........",".........oooooo.........","........ssssssss........"] },
      { ms: 80, head: [12,1], px: ["........................","..........oooo..........",".........oLLLLo.........","........oLLLLLBo........",".......oLWWLLLWDo.......",".......oLWLLLWBDo.......","......oLLLLBWBBDDo......","......oLLLBWBBBDDo......","......oLLBWBBBBDDo......","......oLBBBBBBBqDo......","......oLBBBBBBBDDo......","......oBBpBBBBBDDo......",".......oDBBBBBDDo.......","........oDqDDDDo........",".........oooooo.........","........ssssssss........"] },
      { ms: 90, head: [12,1], px: ["........................","..........oooo..........",".........oLLLLo.........","........oLLLLLBo........",".......oLWWLLLBDo.......",".......oLWLLLBBDo.......","......oLLLLBBBBDLo......","......oLLLBBBBBLDo......","......oLLBBBBBLDDo......","......oLBBBBBLBqDo......","......oLBBBBLBBDDo......","......oBBpBBBBBDDo......",".......oDBBBBBDDo.......","........oDqDDDDo........",".........oooooo.........","........ssssssss........"] },
      { ms: 2200, head: [12,1], px: ["........................","..........oooo..........",".........oLLLLo.........","........oLLLLLBo........",".......oLWWLLLBDo.......",".......oLWLLLBBDo.......","......oLLLLBBBBDDo......","......oLLLBBBBBDDo......","......oLLBBBBBBDDo......","......oLBBBBBBBqDo......","......oLBBBBBBBDDo......","......oBBpBBBBBDDo......",".......oDBBBBBDDo.......","........oDqDDDDo........",".........oooooo.........","........ssssssss........"], exit: true },
      { ms: 110, head: [12,1], px: ["........................",".....W....oooo..........","....WWW..oLLLLo.........",".....W..oLLLLLBo........",".......oWWWLLLBDo.......",".......oLWLLLBBDo.......","......oLLLLBBBBDDo......","......oLLLBBBBBDDo......","......oLLBBBBBBDDo......","......oLBBBBBBBqDo......","......oLBBBBBBBDDo......","......oBBpBBBBBDDo......",".......oDBBBBBDDo.......","........oDqDDDDo........",".........oooooo.........","........ssssssss........"], exit: true },
      { ms: 90, head: [12,1], px: ["........................","..........oooo..........",".....W...oLLLLo.........","........oLLLLLBo........",".......oLWWLLLBDo.......",".......oLWLLLBBDo.......","......oLLLLBBBBDDo......","......oLLLBBBBBDDo......","......oLLBBBBBBDDo......","......oLBBBBBBBqDo......","......oLBBBBBBBDDo......","......oBBpBBBBBDDo......",".......oDBBBBBDDo.......","........oDqDDDDo........",".........oooooo.........","........ssssssss........"], exit: true },
      { ms: 1800, head: [12,1], px: ["........................","..........oooo..........",".........oLLLLo.........","........oLLLLLBo........",".......oLWWLLLBDo.......",".......oLWLLLBBDo.......","......oLLLLBBBBDDo......","......oLLLBBBBBDDo......","......oLLBBBBBBDDo......","......oLBBBBBBBqDo......","......oLBBBBBBBDDo......","......oBBpBBBBBDDo......",".......oDBBBBBDDo.......","........oDqDDDDo........",".........oooooo.........","........ssssssss........"], exit: true },
    ] },
    "working": { loop: true, frames: [
      { ms: 110, head: [12,2], px: ["........................","........................","..........oooo..........",".........oLLLLo.........","........oLLLLLBo........",".......oLWWLLLBDo.......","......oLLWLLBBBDDo......","......oLLLLBBBBDDo......","......oLLLBBBBBDDo......","......oLLBBBBBBqDo......","......oLBBBBBBBDDo......","......oBBpBBBBBDDo......","......oDBBBBBBBDDo......",".......oDDqDDDDDo.......","........oooooooo........",".......ssssssssss......."], exit: true },
      { ms: 100, head: [13,1], px: ["........................","............oooo........","..........ooLLLLo.......",".........oLLLLLBo.......","........oLWWLLLBDo......","........oLWLLLBBDo......",".......oLLLLBBBBDDo.....",".......oLLLBBBBBDDo.....",".......oLLBBBBBBDDo.....",".......oLBBBBBBBqDo.....",".......oLBBBBBBBDDo.....",".......oBBpBBBBBDDo.....",".......oDBBBBBBDDo......","........oDDqDDDDo.......",".........ooooooo........","........ssssssss........"] },
      { ms: 150, head: [14,2], px: ["........................","........................",".............oooo.......","...........ooLLLLo......","..........oLWWLLBo......",".........oLWLLLBBDo.....","........oLLLLBBBDDo.....","........oLLLBBBBBDDo....",".......oLLBBBBBBBDDo....",".......oLLBBBBBBBDDo....",".......oLBBBBBBBBqDo....",".......oBBBpBBBBBDDo....","........oDBBBBBBBDDo....",".........oDqDDDDDDo.....","..........oooooooo......",".........ssssssss......."] },
      { ms: 100, head: [13,1], px: ["........................","............oooo........","..........ooLLLLo.......",".........oLLLLLBo.......","........oLWWLLLBDo......","........oLWLLLBBDo......",".......oLLLLBBBBDDo.....",".......oLLLBBBBBDDo.....",".......oLLBBBBBBDDo.....",".......oLBBBBBBBqDo.....",".......oLBBBBBBBDDo.....",".......oBBpBBBBBDDo.....",".......oDBBBBBBDDo......","........oDDqDDDDo.......",".........ooooooo........","........ssssssss........"] },
      { ms: 110, head: [12,2], px: ["........................","........................","..........oooo..........",".........oLLLLo.........","........oLLLLLBo........",".......oLWWLLLBDo.......","......oLLWLLBBBDDo......","......oLLLLBBBBDDo......","......oLLLBBBBBDDo......","......oLLBBBBBBqDo......","......oLBBBBBBBDDo......","......oBBpBBBBBDDo......","......oDBBBBBBBDDo......",".......oDDqDDDDDo.......","........oooooooo........",".......ssssssssss......."], exit: true },
      { ms: 100, head: [10,1], px: ["........................","........oooo............",".......oLLLLoo..........",".......oLLLLLBo.........","......oLWWLLLBDo........","......oLWLLLBBDo........",".....oLLLLBBBBDDo.......",".....oLLLBBBBBDDo.......",".....oLLBBBBBBDDo.......",".....oLBBBBBBBqDo.......",".....oLBBBBBBBDDo.......",".....oBBpBBBBBDDo.......","......oDBBBBBBDDo.......",".......oDqDDDDDo........","........ooooooo.........","........ssssssss........"] },
      { ms: 150, head: [9,2], px: ["........................","........................",".......oooo.............","......oLLLLoo...........","......oLWWLLBo..........",".....oLWLLLBBDo.........",".....oLLLLBBBDDo........","....oLLLLBBBBDDo........","....oLLLBBBBBBDDo.......","....oLLBBBBBBpDDo.......","....oLBBBBBBBBDDo.......","....oBBBBBBBBBDDo.......","....oDBpBBBBBDDo........",".....oDDqDDDDDo.........","......oooooooo..........",".......ssssssss........."] },
      { ms: 100, head: [10,1], px: ["........................","........oooo............",".......oLLLLoo..........",".......oLLLLLBo.........","......oLWWLLLBDo........","......oLWLLLBBDo........",".....oLLLLBBBBDDo.......",".....oLLLBBBBBDDo.......",".....oLLBBBBBBDDo.......",".....oLBBBBBBBqDo.......",".....oLBBBBBBBDDo.......",".....oBBpBBBBBDDo.......","......oDBBBBBBDDo.......",".......oDqDDDDDo........","........ooooooo.........","........ssssssss........"] },
    ] },
  },
}
