// Hand-drawn by the artist; data only. Generated from art/egg3/egg3.art by art/build.py
import type { PetSheet } from '../pets.ts'

export const EGG3_SHEET: PetSheet = {
  w: 24,
  h: 16,
  palette: {"o":"#2b1f2a","W":"#fffdf6","L":"#f7ecd6","B":"#e9d5b0","D":"#c9a985","p":"#d77757","q":"#a8553b","s":"#26262e","K":"#5e4440"},
  animations: {
    "idle": { loop: true, frames: [
      { ms: 1500, head: [12,1], px: ["........................","..........oooo..........",".........oLLKLo.........","........oLLLKLBo........",".......oLWWLLKBDo.......",".......oLWLLLBBDo.......","......ooLLLoBBBoDo......","......oLoLoBoBoDDo......","......oLLoBBBoBDDo......","......oLBBBBBBBqDo......","......oLBBBBBBBDDo......","......oBBpBBBBKKDo......",".......oDBBBKKDDo.......","........oDqDDDDo........",".........oooooo.........","........ssssssss........"], exit: true },
      { ms: 80, head: [12,1], px: ["........................","..........oooo..........",".........oLLKWo.........","........oLLLKLBo........",".......oLWWWLKBDo.......",".......oLWWLLBBDo.......","......ooLWLoBBBoDo......","......oLoLoBoBoDDo......","......oLLoBBBoBDDo......","......oLBBBBBBBqDo......","......oLBBBBBBBDDo......","......oBBpBBBBKKDo......",".......oDBBBKKDDo.......","........oDqDDDDo........",".........oooooo.........","........ssssssss........"] },
      { ms: 80, head: [12,1], px: ["........................","..........oooo..........",".........oLLKLo.........","........oLLLKLBo........",".......oLWWLLKWDo.......",".......oLWLLLWBDo.......","......ooLLLoWBBoDo......","......oLoLoWoBoDDo......","......oLLoWBBoBDDo......","......oLBBBBBBBqDo......","......oLBBBBBBBDDo......","......oBBpBBBBKKDo......",".......oDBBBKKDDo.......","........oDqDDDDo........",".........oooooo.........","........ssssssss........"] },
      { ms: 90, head: [12,1], px: ["........................","..........oooo..........",".........oLLKLo.........","........oLLLKLBo........",".......oLWWLLKBDo.......",".......oLWLLLBBDo.......","......ooLLLoBBBoLo......","......oLoLoBoBoLDo......","......oLLoBBBoLDDo......","......oLBBBBBLBqDo......","......oLBBBBLBBDDo......","......oBBpBBBBKKDo......",".......oDBBBKKDDo.......","........oDqDDDDo........",".........oooooo.........","........ssssssss........"] },
      { ms: 2200, head: [12,1], px: ["........................","..........oooo..........",".........oLLKLo.........","........oLLLKLBo........",".......oLWWLLKBDo.......",".......oLWLLLBBDo.......","......ooLLLoBBBoDo......","......oLoLoBoBoDDo......","......oLLoBBBoBDDo......","......oLBBBBBBBqDo......","......oLBBBBBBBDDo......","......oBBpBBBBKKDo......",".......oDBBBKKDDo.......","........oDqDDDDo........",".........oooooo.........","........ssssssss........"], exit: true },
      { ms: 110, head: [12,1], px: ["........................",".....W....oooo..........","....WWW..oLLKLo.........",".....W..oLLLKLBo........",".......oWWWLLKBDo.......",".......oLWLLLBBDo.......","......ooLLLoBBBoDo......","......oLoLoBoBoDDo......","......oLLoBBBoBDDo......","......oLBBBBBBBqDo......","......oLBBBBBBBDDo......","......oBBpBBBBKKDo......",".......oDBBBKKDDo.......","........oDqDDDDo........",".........oooooo.........","........ssssssss........"], exit: true },
      { ms: 90, head: [12,1], px: ["........................","..........oooo..........",".....W...oLLKLo.........","........oLLLKLBo........",".......oLWWLLKBDo.......",".......oLWLLLBBDo.......","......ooLLLoBBBoDo......","......oLoLoBoBoDDo......","......oLLoBBBoBDDo......","......oLBBBBBBBqDo......","......oLBBBBBBBDDo......","......oBBpBBBBKKDo......",".......oDBBBKKDDo.......","........oDqDDDDo........",".........oooooo.........","........ssssssss........"], exit: true },
      { ms: 1800, head: [12,1], px: ["........................","..........oooo..........",".........oLLKLo.........","........oLLLKLBo........",".......oLWWLLKBDo.......",".......oLWLLLBBDo.......","......ooLLLoBBBoDo......","......oLoLoBoBoDDo......","......oLLoBBBoBDDo......","......oLBBBBBBBqDo......","......oLBBBBBBBDDo......","......oBBpBBBBKKDo......",".......oDBBBKKDDo.......","........oDqDDDDo........",".........oooooo.........","........ssssssss........"], exit: true },
    ] },
    "working": { loop: true, frames: [
      { ms: 110, head: [12,2], px: ["........................","........................","..........oooo..........",".........oLLKLo.........","........oLLLKLBo........",".......oLWWLLKBDo.......","......ooLWLoBBBoDo......","......oLoLoBoBoDDo......","......oLLoBBBoBDDo......","......oLLBBBBBBqDo......","......oLBBBBBBBDDo......","......oBBpBBBBKKDo......","......oDBBBBKKBDDo......",".......oDDqDDDDDo.......","........oooooooo........",".......ssssssssss......."], exit: true },
      { ms: 100, head: [13,1], px: ["........................","............oooo........","..........ooLLKLo.......",".........oLLLLKBo.......","........oLWWLLLKDo......","........oLWLLLBBDo......",".......ooLLLoBBBoDo.....",".......oLoLoBoBoDDo.....",".......oLLoBBBoBDDo.....",".......oLBBBBBBBqDo.....",".......oLBBBBBBBDDo.....",".......oBBpBBBBKKDo.....",".......oDBBBBKKDDo......","........oDDqDDDDo.......",".........ooooooo........","........ssssssss........"] },
      { ms: 150, head: [14,2], px: ["........................","........................",".............oooo.......","...........ooLLKLo......","..........oLWWLKBo......",".........oLWLLLBKDo.....","........ooLLLBBBDDo.....","........oLoLooBBBDDo....",".......oLLBoBBoBooDo....",".......oLLBBBBBoBDDo....",".......oLBBBBBBBBqDo....",".......oBBBpBBBBBDDo....","........oDBBBBBBKKDo....",".........oDqDDKKDDo.....","..........oooooooo......",".........ssssssss......."] },
      { ms: 100, head: [13,1], px: ["........................","............oooo........","..........ooLLKLo.......",".........oLLLLKBo.......","........oLWWLLLKDo......","........oLWLLLBBDo......",".......ooLLLoBBBoDo.....",".......oLoLoBoBoDDo.....",".......oLLoBBBoBDDo.....",".......oLBBBBBBBqDo.....",".......oLBBBBBBBDDo.....",".......oBBpBBBBKKDo.....",".......oDBBBBKKDDo......","........oDDqDDDDo.......",".........ooooooo........","........ssssssss........"] },
      { ms: 110, head: [12,2], px: ["........................","........................","..........oooo..........",".........oLLKLo.........","........oLLLKLBo........",".......oLWWLLKBDo.......","......ooLWLoBBBoDo......","......oLoLoBoBoDDo......","......oLLoBBBoBDDo......","......oLLBBBBBBqDo......","......oLBBBBBBBDDo......","......oBBpBBBBKKDo......","......oDBBBBKKBDDo......",".......oDDqDDDDDo.......","........oooooooo........",".......ssssssssss......."], exit: true },
      { ms: 100, head: [10,1], px: ["........................","........oooo............",".......oLLKLoo..........",".......oLLKLLBo.........","......oLWWLKLBDo........","......oLWLLLBBDo........",".....ooLLLoBBBoDo.......",".....oLoLoBoBoDDo.......",".....oLLoBBBoBDDo.......",".....oLBBBBBBBqDo.......",".....oLBBBBBBBDDo.......",".....oBBpBBBBKKDo.......","......oDBBBKKBDDo.......",".......oDqDDDDDo........","........ooooooo.........","........ssssssss........"] },
      { ms: 150, head: [9,2], px: ["........................","........................",".......oooo.............","......oLKLLoo...........","......oLKWLLBo..........",".....oLWLKLBBDo.........",".....oLLLLBBBoDo........","....oLLLLooBoDDo........","....oooLoBBoBBDDo.......","....oLLoBBBBBpDDo.......","....oLBBBBBBBBDDo.......","....oBBBBBBBKKDDo.......","....oDBpBBKKBDDo........",".....oDDqDDDDDo.........","......oooooooo..........",".......ssssssss........."] },
      { ms: 100, head: [10,1], px: ["........................","........oooo............",".......oLLKLoo..........",".......oLLKLLBo.........","......oLWWLKLBDo........","......oLWLLLBBDo........",".....ooLLLoBBBoDo.......",".....oLoLoBoBoDDo.......",".....oLLoBBBoBDDo.......",".....oLBBBBBBBqDo.......",".....oLBBBBBBBDDo.......",".....oBBpBBBBKKDo.......","......oDBBBKKBDDo.......",".......oDqDDDDDo........","........ooooooo.........","........ssssssss........"] },
    ] },
  },
}
